# Generated by Django 4.0.4 on 2022-05-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='edesignation',
            field=models.CharField(max_length=150),
        ),
    ]
